### ISSUE TITLE
Use Secondary camera

### ISSUE THREAD

**Issue by elz0ux** [myflashlab/AR-ANE-Samples#1]
That's a nice and helpful ANE, but i couldn't find a way to use the front camera of the device. how to do that ?!

**Comment by myflashlab** [comment]
you can do this in AREL scripting. please read here for more instruction
http://helpdesk.metaio.com/questions/21451/switch-back-and-front-cameras-on-metaio-creator

FYI: you can write AREL in metaio creator AREL IDE or simply edit the .js files in any text editor.

> you'll have to use AREL scripting in Creator to switch camera index from 0 (usually the device' main camera) to 1 (usually secondary camera) and maybe also back when you're done.
http://helpdesk.metaio.com/questions/3748/startcamera-in-arel
ps: shutting down the camera and starting up the other one can take some time. maybe you'll also have to wait some time till shutdown has completed and you'll be able to start the other camera.

**Comment by bernardkh** [comment]
I bought the license but I need to know how I can use the front camera of the device instead of the back one, I replaced "downsample" with "1" and "enableYUVpipeline" with "true"
but still no working please I need a help

**Comment by myflashlab** [comment]
@bernardkh as mentioned above, you can use AREL directly. if you have AREL specific questions, [Metaio helpdesk] (http://helpdesk.metaio.com/) is the best place to ask your question. we are responsible for making the metaio SDK to Adobe Air extension and its implementation in Air projects.

**Comment by Cindy-AR** [comment]
Hi Sir,
I am fresh use FB 4.6.
When using AR.ANE, there is a error as below.
"Process terminated unexpectedly.

Error: The extension com.doitflash.air.extensions.ar has either a namespace version or library.swf with a version that is incompatible with the applications namespace or root SWF."

**Comment by majidHejazi** [comment]
Hi @Cindy-AR your question is not related to this issue actually, it would be better you create a new issue for this but anyway, you need to mention at least version 15.0 of Adobe AIR in your manifest file.

`<application xmlns="http://ns.adobe.com/air/application/15.0">`

**Comment by Cindy-AR** [comment]
Hi,

I had use 15.0.
I had try 16.0. but still the same error.

Have any suggestions?

Many thanks

**Comment by myflashlab** [comment]
maybe you should try setting your -swf-version to 25 or higher?

**Comment by Cindy-AR** [comment]
Hi Sir,

Many thanks again.

Regarding "In the Additional compiler arguments field, type -swf-version 25" , the ar.ane can be complier.
there is a ArgumentError:  the extension context does not have a method with the name command when debug in  ( _ex=new MyAR() )

have any suggestions for this error?

ps . my developer tool  : FB4.6, free metaio sdk and your ANE folder.

**Comment by myflashlab** [comment]
so, you did managed to compile the .ane? anyway, about the other ArgumentError you have, it seems like you have not correctly embeded the extension into your project. we have a FlashBuilder demo project which you can easily run without having to set everything yourself from scratch! https://github.com/myflashlab/AR-ANE-Samples/tree/master/FlashBuilder

**Comment by Cindy-AR** [comment]
Hi Sir,

Many thanks.
Regarding a FlashBuilder demo, there still is a error (new MyAR()) which was not  a the with name command.
Is the com folder losing air API or Air SDK lose some api about AR H

Having any suggestions about this error ?

**Comment by myflashlab** [comment]
@Cindy-AR I already explained this in my other post above. I am closing this ticket now because the ongoing conversation has nothing to do with ANE implementation! and we like to keep the issues section clean and helpful for all developers. in the meanwhile, Cindy, I suggest you to do some googling and get more familiar with how .ane extensions are used in Air projects.
