### ISSUE TITLE
Unable to compile samples in Adobe Animate

### ISSUE THREAD

**Issue by wigginsray** [myflashlab/AR-ANE-Samples#12]
Before opening a new issue, make sure you are using the latest available ANE. If the ANE is dependent on other libraries or dependencies, also make sure they are the latest versions.

## Environment ##
* Android API Version: n/a
* iOS Version: 9.3.5
* AIR SDK Version: 27.0.0.132 (also tried 27.0.0.116)

## Problem Description ##
Error is:

Error creating files.

Unknown error.
unexpected failure: null
java.io.EOFException
at
java.io.RandomAccessFile.readUnsignedByte(RandomAccessFile.java.689)
at
com.adobe.air.ipa.MachoSigner.readIntLE(MachoSigner.java:1037)
at
com.adobe.air.ipa.MachoSigner.sign(MachoSigner.java.291)
at
com.adobe.air.ipa.MachoSigner.sign(MachoSigner.java.107)
at
com.adobe.air.ipa.IPASigner.signMacho(IPASigner.java.253)
at
com.adobe.air.ipa.IPAOutputStream.finalizeFrameworkSign(IPAOutputStream.java:1362)
at
com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java:94)
at
com.adobe.air.ipa.IPAPackager.createPackage(IPAPackager.java:291)
at
com.adobe.air.ADT.parseArgsAndGo(ADT.java:673)
at 
com.adobe.air.ADT.run(ADT.java:471)
at
com.adobe.air.ADT.main(ADT.java.521)

* Copy your manifest ```.xml``` file.
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!-- 
	Usage:

	To localize the description, use the following format for the description element.
	<description>
	<text xml:lang="en">English App description goes here</text>
	<text xml:lang="fr">French App description goes here</text>
	<text xml:lang="ja">Japanese App description goes here</text>
	</description>

	To localize the name, use the following format for the name element.
	<name>
	<text xml:lang="en">English App name goes here</text>
	<text xml:lang="fr">French App name goes here</text>
	<text xml:lang="ja">Japanese App name goes here</text>
	</name>
-->
<application xmlns="http://ns.adobe.com/air/application/27.0">
  <id>com.simplymg.rockwell.ar2017</id>
  <versionNumber>1.0</versionNumber>
  <filename>MyTestAR</filename>
  <description/>
  <name>MyTestAR</name>
  <copyright/>
  <initialWindow>
    <content>MyTestAR.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <aspectRatio>portrait</aspectRatio>
    <renderMode>cpu</renderMode>
    <autoOrients>false</autoOrients></initialWindow>
  <icon>
    <image48x48>icons/icons/icon_48.png</image48x48>
    <image72x72>icons/icons/icon_72.png</image72x72>
    <image50x50>icons/icons/icon_50.png</image50x50>
    <image100x100>icons/icons/icon_100.png</image100x100>
    <image144x144>icons/icons/icon_144.png</image144x144>
    <image40x40>icons/icons/icon_40.png</image40x40>
    <image76x76>icons/icons/icon_76.png</image76x76>
    <image57x57>icons/icons/icon_57.png</image57x57>
  </icon>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  <iPhone>
    <InfoAdditions><![CDATA[
  <!--iOS 9.0 or higher can support this ANE-->
  <key>MinimumOSVersion</key>
  <string>9.0</string>
  <key>UIPrerenderedIcon</key>
  <true/>
  <key>UIStatusBarStyle</key>
  <string>UIStatusBarStyleBlackOpaque</string>
  <key>UIRequiresPersistentWiFi</key>
  <string>NO</string>
  <key>UIDeviceFamily</key>
  <array>
    <string>2</string>
  </array>
  <key>NSLocationWhenInUseUsageDescription</key>
  <string>Access to your Geo Data is needed to diplay augmented reality images on your screen.</string>
  <key>NSCameraUsageDescription</key>
  <string>Access to the camera is needed to display augmented reality content on top of your camera image.</string>
]]></InfoAdditions>
    <requestedDisplayResolution>standard</requestedDisplayResolution>
  </iPhone>
  <extensions>
    <extensionID>com.myflashlab.air.extensions.ar</extensionID>
    <extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
  </extensions>
</application>
```
* Copy your Actionscript code.
```actionscript
Unmodified Main.as from samples. As part of my testing, I also tried a modification to Main.as making it  extend MovieClip instead of Sprite
```

## Steps to Reproduce ##
Tried downloading the Framework based on the link provided in the documentation. Also tried downloading the IOS Wikitude framework from Wikitude (latest version) both IOS Native and IOS Javascript flavors. No Joy.

## Known Workarounds ##
I can compile if I leave out the Frameworks folder - but, of course, that doesn't allow the application to function - but it is where the error appears to be triggered.

--

In an ideal world I'd like to have a sample project specifically setup for Adobe Animate - but at the very least, perhaps some clues on how to properly compile the Framework.

I was using the AR-ANE-Samples-Master files. I've linked to all the proper ANE's required (both with and without the Android Support ane (I'm only compiling for IOS))

My ar.ane appears to be V1.0.0. 
Adobe Animate 18.0 (build 107)

**Comment by myflashlab** [comment]
Please confirm the following:

1. you used the wikitude SDK link found here: https://github.com/myflashlab/AR-ANE-Samples/tree/master/AIR/Frameworks
2. for iOS build, you need a mac to compile your project.

**Comment by wigginsray** [comment]
Funny you should say that. I just did a test on my Mac and it compiled OK. The individual scenes themselves aren't working - I get an error 1010 The given architect world is nil. I briefly get the Powered by Wikitude logo, but the camera view is black. I've included the assets folder in my included files. Getting closer.

**Comment by wigginsray** [comment]
Further progress. When I included the assets folder, the sample was looking for the files to be on the root not in a subfolder assets. Corrected that and I'm no longer getting the error. Still no camera, however. I put the assets to the root of the project and included them there. Clue that it helped is that I now get a close button on the camera view that wasn't there before, I also don't get the nil error. 

I must be close.

**Comment by labinc** [comment]
i got this error 

[SWF] Main.swf - 47112 bytes after decompression
ArgumentError: Error #3500: The extension context does not have a method with the name command.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.myflashlab.air.extensions.dependency::OverrideAir()
	at com.myflashlab.air.extensions.dependency::OverrideAir$/applyToAneLab()
	at com.myflashlab.air.extensions.nativePermissions::PermissionCheck()
	at Main()[D:\Trabajo\AR as3\AR-ANE-Samples-master\AIR\src\Main.as:47]
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at ADLAppEntry/run()
	at global/runtime::ADLEntry()
[UnloadSWF] Main.swf
Test Movie terminated.

**Comment by myflashlab** [comment]
> ArgumentError: Error #3500: The extension context does not have a method with the name command.

Such errors simply means that the ANE is not properly implemented into your project. Or this could happen if you were testing on a simulator.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
