### ISSUE TITLE
Listener to image detection

### ISSUE THREAD

**Issue by tomergott** [myflashlab/AR-ANE-Samples#15]
Hi,
i am able to run the samples successfully and detect images which was what i wanted.
now i want to ask if there is any EventListener that can be triggered when something happen in the AR?
Let's say i want to show a movieclip from my library. can i do it?
Thank you
Tomer.

**Comment by myflashlab** [comment]
Well, we have introduced tools for sending messages from AR JS to AIR and vice versa, you can use that to tell your AIR side that something has happened on the JS side.

**Comment by tomergott** [comment]
Ok i have read that but i understand that i cant show Movieclips on the ar camera but only images or viseo am i correct?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
