### ISSUE TITLE
Android: AR.VideoDrawable not load from applicationStorageDirectory

### ISSUE THREAD

**Issue by chutawat** [myflashlab/AR-ANE-Samples#18]
## Environment ##
* Android Version: 19
* AIR SDK Version: 30.0.0.107
* OS: Windows 10
* Animate CC 2018

## Problem Description ##
```Javascript
World.fore_cloud = new AR.VideoDrawable("assets/foreground.mp4", 2, {
		translate: {
			x: 0,
			y: -2.5,
			z: -5.8
		},
		rotate: {
			heading : 0,
			tilt: -110,			
			roll: 0 
		},
		scale: {
			x: 4.5,
			y: 7,
			z: 7
		},
		zOrder: 1.5,
		isTransparent: true
	});
```

## Steps to Reproduce ##
Setup the project following https://github.com/myflashlab/AR-ANE-Samples/wiki/A.1.-Project-Setup

## Known Workarounds ##
- It can load from documentsDirectory
- Other material such as 3D object and sound (mp3) can be load
- For the same code on iOS. Video can load from applicationStorageDirectory.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
