### ISSUE TITLE
AREL POI 

### ISSUE THREAD

**Issue by HSIN-JU** [myflashlab/AR-ANE-Samples#4]
Hi Sir,
Regarding my custom “Arel POI”, there are no scene radar and POI with a mobile camera.
Pls give me some suggestions and my source is as below(logic.js).

arel.sceneReady(function()
{
console.log("sceneReady");
var sydney = new arel.LLA(25.052049,121.540665, 0);
var newyork = new arel.LLA(25.0669021,121.5533823, 0);
var tokyo = new arel.LLA(25.050833,121.549917, 0);
var munich = new arel.LLA(25.051985,121.544507, 0);
createPOIGeometry("1", "工程", sydney, "工程", "Assets/sydney.jpg");
createPOIGeometry("2", "工程", newyork, "工程", "Assets/newyork.jpg");
createPOIGeometry("3", "工程", tokyo, "工程", "Assets/tokyo.jpg");
createPOIGeometry("4", "工程", munich, "工程", "Assets/munich.jpg");

// This influences minimum and maximum scaling of the geometries (easier for development).
arel.Scene.setLLAObjectRenderingLimits(5, 200);

// Set render frustum accordingly
//arel.Scene.setRendererClippingPlaneLimits(10, 220);
});
function createPOIGeometry(id, title, location, description, thumb)
{
var newPOI = new arel.Object.POI();
newPOI.setID(id);
newPOI.setTitle(title);
newPOI.setLocation(location);
newPOI.setThumbnail(thumb);
newPOI.setIcon("");
newPOI.setVisibility(true,false,true);
newPOI.setLLALimitsEnabled(true);

var popup = new arel.Popup(arel.PopupAttributes);
popup.setDescription("some description of the POI");    
popup.setButtons([new arel.PopupButton("url","url","https://dev.metaio.com") ]);                       

newPOI.setPopup(popup);

arel.Scene.addObject(newPOI);
}
function closeCam()
{
arel.Media.openWebsite("flash://CLOSE_AR");
}

Best Regards,
Cindy CHEN

**Comment by imalitavakoli** [comment]
Your question is related to metio Arel no the AR Extension, if you ask the metio team here: http://helpdesk.metaio.com/
They will help :)

**Comment by HSIN-JU** [comment]
Hi Sir,
Many thanks.
If I want't demo logo( My AR demo.. ), how to do?

2015-05-27 12:15 GMT+08:00 Ali <notifications@github.com>:

**Comment by imalitavakoli** [comment]
Everything is explained clearly in the AR Adobe Air Extension's readme.pdf file:
https://github.com/myflashlab/AR-ANE-SampleMarkerless3DAnimation/raw/master/ReadMe.pdf

You can also read about the Privacy and Policy at the end of the documentation.
