### ISSUE TITLE
metaio is dead?

### ISSUE THREAD

**Issue by jsaade** [myflashlab/AR-ANE-Samples#5]
Hello,
So I wanted to purchase your extension but it relies on metaio licensing.
Tried to go there to purchase a license or check the pricing but it seems they killed their product?

Can I purchase a Metaio SDK license?
Metaio products and subscriptions are no longer available for purchase. Downloads of your previous purchases will be available until December 15th, 2015.

**Comment by marcusmook** [comment]
uh oh.... looks like Apple have just bought Metaio...

http://techcrunch.com/2015/05/28/apple-metaio/#.damins:CTP7

I guess that mean the end of Android support :-(

**Comment by fideldonson** [comment]
Thats just too bad. I have been looking forward to something like this ANE for ages. And was pretty much all set to try it out.
A comment from myflashlab?

**Comment by myflashlab** [comment]
we were away on a vacation and I can see that a LOT has happened while we were away. unfortunately you are right and Apple has bought Metaio which means the end of Metaio AR. we are just back to our office and will need a couple of days to digest this and think of a solution. will keep you updated guys.

**Comment by fideldonson** [comment]
Are there any alternatives to the metaio framework? How about vuforia?

**Comment by jsaade** [comment]
Vuforia does not have an ANE. You could check http://www.in2ar.com/

**Comment by myflashlab** [comment]
@fideldonson we are still investigating on the best alternative.
@jsaade in2ar is slow in performance but surely can be an option for small sized projects

**Comment by fideldonson** [comment]
last i checked in2ar had poor performance and cost 1000 eur for 4 markers. Its out of the scope of all our clients.

@jsaade - i know vuforia does not have an ANE - thats where myflashlab comes into the picture ;-)

**Comment by myflashlab** [comment]
read here http://myappsnippet.com/ar-sdk-ane-poll/

**Comment by vickylance** [comment]
How about trying with Wikitude?
