### ISSUE TITLE
How can i create my own AR markers?

### ISSUE THREAD

**Issue by BBheema** [myflashlab/AR-ANE-Samples#7]
Dear  MyFlashLab Team,

I seen your AR-ANE-Samples-master apk  it works fine.I have a some doubts
1). How can i create my own AR markers?
2).Your ane to support multi markers?

**Comment by myflashlab** [comment]
@BBheema we are still in beta testing steps. please note that this AR extension is built on wikitude SDK and all the features that they support, this ANE supports too. you can read their doc and use their help forum. here we can answer only about ANE integration questions in your Adobe Air projects.
